### ISSUE TITLE
Translation to Turkish language.

### ISSUE THREAD

**Issue by molcay** [workshopper/workshopper-adventure#106]
Hi, 

I have been working to translate [learnyounode](https://github.com/workshopper/learnyounode) to Turkish. I have an issue with menu string (see [img1](#img1) and [img2](#img2)). I think the menu strings coming from **workshopper-adventure**. I also translated this one and I have a PR(#105) for this.

----

#### img1:
![Screen Shot 2019-10-15 at 09 56 31](https://user-images.githubusercontent.com/5708658/66807589-09016380-ef32-11e9-8279-3c09df7f5f36.png)

#### img2:
![Screen Shot 2019-10-15 at 09 56 22](https://user-images.githubusercontent.com/5708658/66807590-09016380-ef32-11e9-9748-df4886fb34f3.png)

**Comment by martinheidegger** [comment]
Fixed in 6.1.0 release
