### ISSUE TITLE
Extract `storage.js` into own package

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/workshopper-adventure#14]
I took the time to abstract the storage functionality into a own tiny module called [`storage.js`](https://github.com/workshopper/workshopper-adventure/blob/39337c1810f7727ee88dde521a5497b2f6e10821/lib/storage.js) that basically can stand alone from the rest of the workshopper. It would be nice if someone could take the time and create a package out of it (preferably with documentation and tests). The code is not very complex should be doable in a relatively short period time.

**Comment by kid-icarus** [comment]
I refactored and wrote some tests and documentation. Module is living here: https://github.com/kid-icarus/webshopper-adventure-storage

The one thing to note is I changed all the methods to be async. Let me know if there's anything else you'd like to see here, and I can make a PR to use it.

**Comment by martinheidegger** [comment]
@kid-icarus This is awesome, thank you for your work! I opened a few issues in the repository that would be lovely if they could be addressed. Particularly the interoperation with older versions of Node might be a biggie. Even though future versions of Workshopper it might be worth considering to drop old node.js version support, I think it might be a bit early for this discussion. I saw that you are using arrow functions that are supported from Version 5 but 4 is still the LTS branch (so it will be around for a while longer).

**Comment by martinheidegger** [comment]
@kid-icarus Thank you for the 1.0.0 release of workshopper-adventure-storage. i agree that the asynchronous API is not a bad thing but it will take a little to adopt all the code.

**Comment by SomeoneWeird** [comment]
@kid-icarus how would you feel about moving that repo into the workshopper org?

**Comment by kid-icarus** [comment]
@SomeoneWeird I'd gladly transfer it over 😄  could I possibly be added to the org?

**Comment by martinheidegger** [comment]
@kid-icarus Invitation sent!

**Comment by kid-icarus** [comment]
Thanks @martinheidegger, glad to be a member of the org!

I tried to transfer ownership to workshopper but got this message, not sure why I need admin access 😕 

![screen shot 2016-09-20 at 8 33 05 am](https://cloud.githubusercontent.com/assets/864752/18677278/2587a610-7f0d-11e6-9251-e1c7cd32b1f6.png)

I'll take a closer look after work.

**Comment by martinheidegger** [comment]
Made you admin!

**Comment by kid-icarus** [comment]
I just tried to transfer ownership, but still encountering the same message. I'm not sure what other permission I need 😕

**Comment by martinheidegger** [comment]
Can you try again?

**Comment by kid-icarus** [comment]
I just tried to transfer again, got the same message. I might have to be owner of the org to transfer ownership. It doesn't matter to me if I have that role permanently but it might be worth switching me for a minute while I transfer unless I'm missing something obvious.

**Comment by martinheidegger** [comment]
Now you have master privileges. _(Note: sorry for my incompetence. I will read more into github org priliveges but now everything should be possible for you)_

**Comment by kid-icarus** [comment]
No worries, they added a lot of new features and permissions recently, I'm also not caught up with it all :)

@SomeoneWeird I went ahead and transferred it over, let me know if there's anything I've missed (I granted access to all members of the workshopper Core team)

**Comment by kid-icarus** [comment]
I think this can be closed now per https://github.com/workshopper/workshopper-adventure/commit/0fbda0d9581c54d74e7dccd8d37f443519ef3245

**Comment by martinheidegger** [comment]
Sadly, no. After publishing I recognized that the workshopper-adventure-storage(w-a-s) doesn't seem to work in some cases and I had to, unfortunately, unpublish the workshopper-adventure with the integration. _(w-a-s has a problem if the folder it wants to store configuration in doesn't exist)_

Tonight it is on the top of my priority list to write a proper issue report / PR.

**Comment by kid-icarus** [comment]
Oh no! I'll create an issue and promptly fix.

**Comment by kid-icarus** [comment]
https://github.com/workshopper/workshopper-adventure-storage/issues/9

**Comment by martinheidegger** [comment]
Okay, this should do the trick, published 5.1.6 as latest version that should include workshopper-adventure-storage@3.0.0 :champagne:
