### ISSUE TITLE
Npm supports man pages but the current system doesn't provide a comfortable way ....

### ISSUE THREAD

**Issue by Annis-Monadjem** [workshopper/workshopper-adventure#28]
Npm supports man pages but the current system doesn't provide a comfortable way to provide the usage. Maybe it should (has to be) generated?
http://www.tldp.org/HOWTO/Man-Page/q3.html

**Comment by martinheidegger** [comment]
Duplicate https://github.com/workshopper/workshopper-adventure/issues/22
