### ISSUE TITLE
Semver major?

### ISSUE THREAD

**Issue by achingbrain** [workshopper/workshopper-adventure#64]
I'm just looking at updating nodebot-workshop from `4.6.1` to `4.7.1` of workshopper-adventure and there's a whole bunch of commits marked `Semver major` between `4.7.0` and `4.7.1` - was this intentional?

**Comment by martinheidegger** [comment]
@achingbrain `workshopper-adventure` not intentional. An error of mine.

Edit: Extending the explanation: I was in hurry publishing workshopper-adventure and accidentally published it as a minor version. Not quite sure how to handle this best 😓

**Comment by SomeoneWeird** [comment]
publish major version, and deprecate the version you accidently published with a massive 'do not use this version lol' message

**Comment by martinheidegger** [comment]
Done. Thank you @achingbrain & @SomeoneWeird
