### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by phillipj** [workshopper/workshopper-adventure#7]
Hi,

are you planning to publish a new version of `workshopper-adventure` by any chance? We're translating some workshops to Norwegian and some have this module as a i18n dependency, but my commits merged in june hasnt been released yet..

**Comment by ralphtheninja** [comment]
@phillipj I'm curious. Which workshops have you translated to Norwegian?

**Comment by ralphtheninja** [comment]
@phillipj Keep in mind that you can use git+ssh in package.json as a workaround until this has been released.

**Comment by phillipj** [comment]
> Which workshops have you translated to Norwegian?

We're done with learnyounode, workshopper and the nodeschool site. We started on javascripting a few months ago which has this package as a dependency. Checkout [@nodeschool-no](https://github.com/nodeschool-no) for more details :)

**Comment by martinheidegger** [comment]
I would like to publish a latest version but I need some help to test the next branch: https://github.com/workshopper/workshopper-adventure/pull/2 Could I bother you to try it out?

**Comment by phillipj** [comment]
Focusing on completing the javascripting problem/solution translation ATM, as it has already taken waaay too long. Could probably take it for a ride next week @martinheidegger, anything special I should look for?

**Comment by martinheidegger** [comment]
Well: mostly if things still work :) There are a lot of details that can go wrong ...

**Comment by phillipj** [comment]
Sorry for not responding before now, it took some week extra to complete the translations... Closing this issue as I see you have published a new version, but I'll do some testing on our refactor branch anyway.
