### ISSUE TITLE
[Issue with README] Broken link

### ISSUE THREAD

**Issue by arku** [workshopper/workshopper-adventure#78]
In the [README](https://github.com/workshopper/workshopper-adventure/blob/master/README.md) file, the link in the following line is broken.
> @linclark has written a good introduction on creating your own workshop, available [here](http://lin-clark.com/blog/2014/07/01/authoring-nodejs-workshopper-lessons/).

**Comment by linclark** [comment]
I recently cleared away all my old posts from my site.

You can find the content here:
https://github.com/linclark/lin-clark.com/blob/master/content/blog/2014/07/01/authoring-nodejs-workshopper-lessons.md

Feel free to take that content and rework/repost it somewhere, or just link
to it on GitHub

**Comment by arku** [comment]
@linclark Ah, I see. I just submitted a PR updating the link. Thanks for the quick reply :+1:

**Comment by martinheidegger** [comment]
Merged the new URL, though I think the content needs updating. Thank you @linclark & @arun1595
