### ISSUE TITLE
Deprecation Warning with Node.js 7.5.0

### ISSUE THREAD

**Issue by MutableLoss** [workshopper/workshopper-adventure#82]
There seems to be an deprecation warning that pops up right after choosing an exercise from the **learnyounode** exercise list.

`(node:115452) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.`

I do want to point out that this is a very new issue, as it exclusively happens with **7.5.0**, and is _not_ found when using Node.js **7.4.0** or earlier. 

While I'm not sure, my apologies if this a misplaced issue for adventure-storage, but I can definitely say it is an _adventure-only_ issue, as this warning is not experienced in **learnyoumongo** when using _workshopper_.

**Comment by martinheidegger** [comment]
Thank you for that issue. The culprit to this deprecation warning seems to be [in wrappedexec#L10](https://github.com/workshopper/workshopper-wrappedexec/blob/5700e238f2d3f303b7f114b9c27938aada60059e/wrappedexec.js#L10)

wrapped-exec is a dependency of `learnyounode` [here](https://github.com/workshopper/learnyounode/blob/4615d3bc02847850283064be5182bf98afdf4d4f/package.json#L75) but not of workshopper-adventure, as such this is sadly the wrong repository to post this.

**Comment by MutableLoss** [comment]
Ah-ha! Not sure how I missed that that dep, but I will definitely keep that in mind next time. 👍

**Comment by martinheidegger** [comment]
I can accept any PR in workshopper-wrappedexec
