### ISSUE TITLE
Support es6

### ISSUE THREAD

**Issue by AnshulMalik** [workshopper/workshopper-adventure#94]
It's the right time we should support es6 solutions

**Comment by martinheidegger** [comment]
How?

**Comment by AnshulMalik** [comment]
One way I can think is, 
- Use babel to transform to es5 and then evaluate them.

**Comment by martinheidegger** [comment]
I am not sure how that should look like implemented, probably best to send a PR?!

**Comment by martinheidegger** [comment]
The current node version already supports a lot of es6. Closing this issue.
