### ISSUE TITLE
msee broken dependency

### ISSUE THREAD

**Issue by zeckson** [workshopper/workshopper-adventure#96]
Due to a problem in dependency inside `msee` library https://github.com/firede/msee/issues/58
All workshops which use `workshopper-adventure` got incomplete output:
For example:
```bash

  To keep things organized, let's create a folder for this workshop.

  Run this command to make a directory called  (or something else if you
  like):

     mkdir javascripting

  Change directory into the  folder:

     cd javascripting

  Create a file named :
```
As you can see all inline code parts are missed and it's impossible to see problem description correctly.
As a workaround `shrinkwrap` can be used.

**Comment by martinheidegger** [comment]
Released new version of msee, can you check and see if that fixed the issue?

**Comment by zeckson** [comment]
@martinheidegger, yes, I confirm the issue is solved. Thank you!
